In [2]:
#Step 1: Import Required Libraries
import pandas as pd
import numpy as np

In [5]:
#Step 2: Load the Dataset Properly
# Load dataset
df = pd.read_csv('AirQualityUCI.csv')

# Display first 5 rows
df.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),Wind,PT08.S2(NMHC),Solor.R,PT08.S3(NOx),NO2(GT),PT08.S4(NO2),Ozone,Temp,RH,AH
0,10-03-2004,18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,10-03-2004,19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,10-03-2004,20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,10-03-2004,21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,10-03-2004,22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888

In [6]:
#Step 3: Check Dataset Information
# Shape of dataset
print("Shape of Dataset:", df.shape)

# Column names
print("\nColumn Names:")
print(df.columns)

# Dataset information
print("\nDataset Information:")
df.info()

Shape of Dataset: (9357, 15)

Column Names:
Index(['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'Wind',
       'PT08.S2(NMHC)', 'Solor.R', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)',
       'Ozone', 'Temp', 'RH', 'AH'],
      dtype='str')

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           9357 non-null   str
 1   Time           9357 non-null   str
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   int64
 4   NMHC(GT)       9357 non-null   int64
 5   Wind           9357 non-null   float64
 6   PT08.S2(NMHC)  9357 non-null   int64
 7   Solor.R        9357 non-null   int64
 8   PT08.S3(NOx)   9357 non-null   int64
 9   NO2(GT)        9357 non-null   int64
 10  PT08.S4(NO2)   9357 non-null   int64
 11  Ozone          9357 non-null   int64
 12  Temp           9357 non-null   float64
 13  RH             9357 non-null   float64
 14  AH             9357 non-null   float64
dtypes: float64(5), int64(8), str(2)
memory usage: 1.1 MB

In [7]:
#Step 4: Check Missing Values
# Check missing values
print(df.isnull().sum())

Date             0
Time             0
CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         0
Wind             0
PT08.S2(NMHC)    0
Solor.R          0
PT08.S3(NOx)     0
NO2(GT)          0
PT08.S4(NO2)     0
Ozone            0
Temp             0
RH               0
AH               0
dtype: int64

In [8]:
#a DATA CLEANING
#Step 5: Remove Duplicate Rows
# Count duplicate rows
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

# Remove duplicates
df = df.drop_duplicates()

# Check new shape
print("New Shape:", df.shape)

Duplicate Rows: 0
New Shape: (9357, 15)

In [9]:
#Step 6: Handle Missing Values
# Replace -200 with NaN
df.replace(-200, np.nan, inplace=True)
print(df.isnull().sum())

Date                0
Time                0
CO(GT)           1683
PT08.S1(CO)       366
NMHC(GT)         8443
Wind              366
PT08.S2(NMHC)     366
Solor.R          1639
PT08.S3(NOx)      366
NO2(GT)          1642
PT08.S4(NO2)      366
Ozone             366
Temp              366
RH                366
AH                366
dtype: int64

In [11]:
# Step 7: Convert Date and Time into Datetime Format

# Combine Date and Time columns
if 'Date' in df.columns and 'Time' in df.columns:
    
    df['Datetime'] = pd.to_datetime(
        df['Date'] + ' ' + df['Time'],
        dayfirst=True
    )

# Display updated dataset
df.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),Wind,PT08.S2(NMHC),Solor.R,PT08.S3(NOx),NO2(GT),PT08.S4(NO2),Ozone,Temp,RH,AH,Datetime
0,10-03-2004,18:00:00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578,2004-03-10 18:00:00
1,10-03-2004,19:00:00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255,2004-03-10 19:00:00
2,10-03-2004,20:00:00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502,2004-03-10 20:00:00
3,10-03-2004,21:00:00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867,2004-03-10 21:00:00
4,10-03-2004,22:00:00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888,2004-03-10 22:00:00

In [12]:
#Step 8: Statistical Summary
# Statistical summary
df.describe()

,CO(GT),PT08.S1(CO),NMHC(GT),Wind,PT08.S2(NMHC),Solor.R,PT08.S3(NOx),NO2(GT),PT08.S4(NO2),Ozone,Temp,RH,AH,Datetime
count,7674.000000,8991.000000,914.000000,8991.000000,8991.000000,7718.000000,8991.000000,7715.000000,8991.000000,8991.000000,8991.000000,8991.000000,8991.000000,9357
mean,2.152750,1099.833166,218.811816,10.083105,939.153376,246.896735,835.493605,113.091251,1456.264598,1022.906128,18.317829,49.234201,1.025530,2004-09-21 16:00:00
min,0.100000,647.000000,7.000000,0.100000,383.000000,2.000000,322.000000,2.000000,551.000000,221.000000,-1.900000,9.200000,0.184700,2004-03-10 18:00:00
25%,1.100000,937.000000,67.000000,4.400000,734.500000,98.000000,658.000000,78.000000,1227.000000,731.500000,11.800000,35.800000,0.736800,2004-06-16 05:00:00
50%,1.800000,1063.000000,150.000000,8.200000,909.000000,180.000000,806.000000,109.000000,1463.000000,963.000000,17.800000,49.600000,0.995400,2004-09-21 16:00:00
75%,2.900000,1231.000000,297.000000,14.000000,1116.000000,326.000000,969.500000,142.000000,1674.000000,1273.500000,24.400000,62.500000,1.313700,2004-12-28 03:00:00
max,11.900000,2040.000000,1189.000000,63.700000,2214.000000,1479.000000,2683.000000,340.000000,2775.000000,2523.000000,44.600000,88.700000,2.231000,2005-04-04 14:00:00
std,1.453252,217.080037,204.459921,7.449820,266.831429,212.979168,256.817320,48.370108,346.206794,398.484288,8.832116,17.316892,0.403813,NaN

In [13]:
# b DATA INTEGRATION
# Step 9: Create Environmental Quality Index
# Create Environmental Index
if {'Temp', 'RH', 'AH'}.issubset(df.columns):
    
    df['Environmental_Index'] = (
        df['Temp'] + df['RH'] + df['AH']
    ) / 3

# Display data
df.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),Wind,PT08.S2(NMHC),Solor.R,PT08.S3(NOx),NO2(GT),PT08.S4(NO2),Ozone,Temp,RH,AH,Datetime,Environmental_Index
0,10-03-2004,18:00:00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578,2004-03-10 18:00:00,21.085933
1,10-03-2004,19:00:00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255,2004-03-10 19:00:00,20.575167
2,10-03-2004,20:00:00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502,2004-03-10 20:00:00,22.216733
3,10-03-2004,21:00:00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867,2004-03-10 21:00:00,23.928900
4,10-03-2004,22:00:00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888,2004-03-10 22:00:00,23.862933

In [14]:
#Step 10: Create Integrated Dataset
# Select important columns
selected_columns = []

for col in ['Datetime', 'CO(GT)', 'NMHC(GT)', 'NO2(GT)',
            'Temp', 'RH', 'AH', 'Environmental_Index']:
    
    if col in df.columns:
        selected_columns.append(col)

# Create integrated dataset
integrated_df = df[selected_columns]

# Display integrated dataset
print(integrated_df.head())

             Datetime  CO(GT)  NMHC(GT)  NO2(GT)  Temp    RH      AH  \
0 2004-03-10 18:00:00     2.6     150.0    113.0  13.6  48.9  0.7578
1 2004-03-10 19:00:00     2.0     112.0     92.0  13.3  47.7  0.7255
2 2004-03-10 20:00:00     2.2      88.0    114.0  11.9  54.0  0.7502
3 2004-03-10 21:00:00     2.2      80.0    122.0  11.0  60.0  0.7867
4 2004-03-10 22:00:00     1.6      51.0    116.0  11.2  59.6  0.7888

   Environmental_Index
0            21.085933
1            20.575167
2            22.216733
3            23.928900
4            23.862933

In [15]:
#Step 11: Save Cleaned and Integrated Dataset
# Save final dataset
integrated_df.to_csv('Cleaned_Integrated_AirQuality.csv', index=False)

print("Dataset saved successfully!")

Dataset saved successfully!