In [1]:
import pandas as pd
import numpy as np

In [12]:
#Step 2: Load the Dataset Properly
# Load dataset
df = pd.read_csv('dataset_Facebook.csv')

# Display first 5 rows
df.head()

,pagetotallikes,type,category,postmonth,postweekday,posthour,paid,lifetimeposttotalreach,lifetimeposttotalimpressions,lifetimeengagedusers,lifetimepostconsumers,lifetimepostconsumptions,lifetimepostimpressionsbypeoplewhohavelikedyourpage,lifetimepostreachbypeoplewholikeyourpage,lifetimepeoplewhohavelikedyourpageandengagedwithyourpost,comment,like,share,totalinteractions
0,139441,2,2,12,4,3,0,2752,5091,178,109,159,3078,1640,119,4,79,17,100
1,139441,3,2,12,3,10,0,10460,19057,1457,1361,1674,11710,6112,1108,5,130,29,164
2,139441,2,3,12,3,3,0,2413,4373,177,113,154,2812,1503,132,0,66,14,80
3,139441,2,2,12,2,10,1,50128,87991,2211,790,1119,61027,32048,1386,58,1572,147,1777
4,139441,2,2,12,2,3,0,7244,13594,671,410,580,6228,3200,396,19,325,49,393

In [25]:
#Step 3: Create Column Subset
subset_columns = df[[
    'pagetotallikes',
    'type',
    'category',
    'postmonth',
    'postweekday',
    'lifetimeposttotalreach'
]]

subset_columns.head()

,pagetotallikes,type,category,postmonth,postweekday,lifetimeposttotalreach
0,139441,2,2,12,4,2752
1,139441,3,2,12,3,10460
2,139441,2,3,12,3,2413
3,139441,2,2,12,2,50128
4,139441,2,2,12,2,7244

In [26]:
#Step 4: Create Row Subset
high_reach = df[df['lifetimeposttotalreach'] > 50000]

high_reach.head()

,pagetotallikes,type,category,postmonth,postweekday,posthour,paid,lifetimeposttotalreach,lifetimeposttotalimpressions,lifetimeengagedusers,lifetimepostconsumers,lifetimepostconsumptions,lifetimepostimpressionsbypeoplewhohavelikedyourpage,lifetimepostreachbypeoplewholikeyourpage,lifetimepeoplewhohavelikedyourpageandengagedwithyourpost,comment,like,share,totalinteractions
3,139441,2,2,12,2,10,1,50128,87991,2211,790,1119,61027,32048,1386,58,1572,147,1777
17,138414,2,1,12,2,12,1,53264,111785,1706,1103,1655,92512,39776,1307,15,678,20,713
61,138185,2,1,11,3,2,1,50912,164528,630,513,952,54653,12704,346,8,144,10,162
67,138185,2,1,11,7,3,1,53456,93790,1576,995,1469,32646,14912,884,20,697,70,787
71,137893,4,1,11,5,3,1,100768,220447,2101,1735,2331,59658,18880,885,17,449,84,550

In [27]:
#Step 5: Create Type-Based Subset
photo_posts = df[df['type'] == 'Photo']

photo_posts.head()

Empty DataFrame
Columns: [pagetotallikes, type, category, postmonth, postweekday, posthour, paid, lifetimeposttotalreach, lifetimeposttotalimpressions, lifetimeengagedusers, lifetimepostconsumers, lifetimepostconsumptions, lifetimepostimpressionsbypeoplewhohavelikedyourpage, lifetimepostreachbypeoplewholikeyourpage, lifetimepeoplewhohavelikedyourpageandengagedwithyourpost, comment, like, share, totalinteractions]
Index: []

In [28]:
# B Merge Data
#Step 6: Create Two DataFrames
df1 = df[['type', 'category', 'postmonth']]

df2 = df[['like', 'share', 'comment']]

In [29]:
#Step 7: Merge DataFrames
merged_df = pd.concat([df1, df2], axis=1)

merged_df.head()

   type  category  postmonth  like  share  comment
0     2         2         12    79     17        4
1     3         2         12   130     29        5
2     2         3         12    66     14        0
3     2         2         12  1572    147       58
4     2         2         12   325     49       19

In [30]:
merged_df.to_csv('Merged_Facebook_Data.csv', index=False)

print("Dataset saved successfully!")

Dataset saved successfully!